### ISSUE TITLE
测试时候出现cuda out of memory

### ISSUE THREAD

**Issue by xiacoder** [taishan1994/pytorch_bert_multi_classification#2]
模型训练结束后，进行测试时候报了cuda out of memory
model, optimizer, epoch, loss = self.load_ckp(model, optimizer, checkpoint)这一行代码

**Comment by taishan1994** [comment]
> 模型训练结束后，进行测试时候报了cuda out of memory model, optimizer, epoch, loss = self.load_ckp(model, optimizer, checkpoint)这一行代码

那是因为GPU显存不够，调小测试时的batch_size
